// _tools_index.js - generate the TOOL INVENTORY of Test/ (and check it is fresh).
//
// WHY: 80+ helper scripts live in Test/, but only a handful are described in the
// docs, so a tool could not be found without knowing its NAME ("сейчас их не
// найти, не зная имени" - user, 2026-10-04). The inventory is GENERATED from the
// tools themselves (each one starts with a comment block: a one-line summary plus
// an optional Usage: block), so it cannot drift from the code.
//
// Usage:
//   node Test/_tools_index.js           # rewrite the block in Test/README.md
//   node Test/_tools_index.js --check   # exit 1 when the block is stale
//   node Test/_tools_index.js --print   # print the block, touch nothing
//
// The generated block in Test/README.md is delimited by
//   <!-- TOOLS:START --> ... <!-- TOOLS:END -->
// and mh_test pins it (B59), so a new tool added without refreshing the inventory
// fails the harness - that is the formalized requirement, not a convention.
'use strict';
const fs = require('fs');
const path = require('path');

const TEST = __dirname;
const README = path.join(TEST, 'README.md');
const SELF = path.basename(__filename);
const START = '<!-- TOOLS:START -->';
const END = '<!-- TOOLS:END -->';
// Files described by hand in the README (harness) - not repeated in the table.
const SKIP = new Set([SELF, 'mh_test.js', 'SCRIPTING-API-TEST.js', 'README.md']);

// Category by filename prefix, in display order.
const CATS = [
  [/^(cdp_|ac_swlog_)/, 'CDP / SW-console tools (drive a browser through the DevTools port)'],
  [/^(_probe_|_bench_)/, 'Probes & benchmarks (a PHYSICAL test is needed: the engine drops synthetic input)'],
  [/^zone_/, 'Zone tools (test triggers, probes, the regression suite)'],
  [/^(engine_|patch_)/, 'Engine & patch tools (the v19 zone-table patch)'],
  [/^(build_|deploy_)/, 'Build & deploy'],
  [/^(_?ac_|acs_|ac_keys|ac_zone_helper)/, 'Input & state probes (keys, mouse, audio, settings audit)'],
];

function category(name) {
  for (const [re, title] of CATS) if (re.test(name)) return title;
  return 'Other';
}

// First comment block of a tool -> { summary, usage[] }.
function describe(file) {
  let text;
  try { text = fs.readFileSync(file, 'utf8'); } catch (e) { return null; }
  const lines = text.split(/\r?\n/).slice(0, 80);
  const isComment = l => /^\s*(\/\/|#)/.test(l);
  const block = [];
  for (const l of lines) {
    if (isComment(l)) block.push(l.replace(/^\s*(\/\/|#)\s?/, '').trimEnd());
    else if (block.length) break;
    else if (l.trim() === '') continue;
    else break;
  }
  if (!block.length) return { summary: '(no header comment)', usage: [] };
  let summary = block[0].replace(/^\S+\.(js|ps1|cs|md)\s*[-:]\s*/, '').trim();
  if (!summary) summary = '(no header comment)';
  const usage = [];
  const ui = block.findIndex(l => /^Usage:?/i.test(l));
  if (ui >= 0) {
    for (let i = ui + 1; i < block.length; i++) {
      const l = block[i];
      if (!l.trim()) break;
      usage.push(l.trim());
    }
  }
  return { summary, usage };
}

function build() {
  const files = fs.readdirSync(TEST, { withFileTypes: true })
    .filter(d => d.isFile() && !SKIP.has(d.name))
    .filter(d => /\.(js|ps1|cs)$/i.test(d.name))
    .map(d => d.name).sort();

  const groups = new Map();
  for (const name of files) {
    const cat = category(name);
    if (!groups.has(cat)) groups.set(cat, []);
    const d = describe(path.join(TEST, name));
    groups.get(cat).push({ name, ...(d || { summary: '(unreadable)' }) });
  }

  const out = [];
  out.push(START);
  out.push('<!-- Generated by `node Test/_tools_index.js` - do NOT edit this block by hand.');
  out.push('     mh_test pins it (B59): a new tool without a refreshed inventory fails the harness. -->');
  out.push('');
  out.push(`**Tool inventory** (${files.length} tools on disk). One line per tool, taken from its own header comment.`);
  // Emit the categories in CATS order, "Other" last - a Map would order them by
  // the first file that happened to match.
  const order = CATS.map(([, title]) => title);
  if (groups.has('Other')) order.push('Other');
  for (const cat of order) {
    const items = groups.get(cat);
    if (!items) continue;
    out.push('');
    out.push(`#### ${cat}`);
    out.push('');
    for (const it of items) {
      out.push(`- **\`${it.name}\`** — ${it.summary}`);
      if (it.usage.length) out.push(`  \`\` ${it.usage.join('  |  ')} \`\``);
    }
  }
  out.push('');
  out.push(END);
  return out.join('\n');
}

function splice(readme, block) {
  const i = readme.indexOf(START);
  const j = readme.indexOf(END);
  if (i < 0 || j < 0) return null;
  return readme.slice(0, i) + block + readme.slice(j + END.length);
}

const mode = process.argv[2] || '';
const block = build();

if (mode === '--print') {
  console.log(block);
  process.exit(0);
}

if (!fs.existsSync(README)) {
  console.log('README missing: ' + README);
  process.exit(2);
}
const readme = fs.readFileSync(README, 'utf8');
const next = splice(readme, block);

if (next === null) {
  console.log(`markers not found in Test/README.md - add\n${START}\n${END}`);
  process.exit(2);
}

if (mode === '--check') {
  if (next === readme) { console.log('TOOLS INVENTORY: up to date'); process.exit(0); }
  const cur = readme.slice(readme.indexOf(START), readme.indexOf(END) + END.length);
  const curLines = cur.split('\n');
  const newLines = block.split('\n');
  const diffs = [];
  for (let i = 0; i < Math.max(curLines.length, newLines.length) && diffs.length < 8; i++) {
    if (curLines[i] !== newLines[i]) diffs.push(`  line ${i + 1}:\n    have: ${curLines[i]}\n    want: ${newLines[i]}`);
  }
  console.log('TOOLS INVENTORY: STALE (run `node Test/_tools_index.js`)');
  diffs.forEach(d => console.log(d));
  process.exit(1);
}

if (next === readme) { console.log('TOOLS INVENTORY: already up to date'); process.exit(0); }
fs.writeFileSync(README, next);
console.log('TOOLS INVENTORY: rewritten in Test/README.md');
